### ISSUE TITLE
Extension not doing anything

### ISSUE THREAD

**Issue by Khaos66** [Quang-Nhan/query-json-lite#1]
This is exactly the extension I was looking for <3

Sadly it doesn't do anything. Hiting the `Run Path` Button doesn't work.

![jsonpath](https://github.com/Quang-Nhan/query-json-lite/assets/4013009/1782dd8d-dcc0-4380-9adb-915d1ded8ffa)

**Comment by Khaos66** [comment]
vscode
> Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by Quang-Nhan** [comment]
Thanks @Khaos66 for raising this issue. 

This bug seems to occur for fresh instalment of Query JSON extension or it is run in a new workspace where it tries to lookup the vs code saved state but failed.

This should now be rectified with the latest version 0.3.0 commit and should be available in vs code to redownload/reload.

Feel free to retry it and confirm if it is now working for you.

**Comment by Khaos66** [comment]
Yes! It worked. Thank you <3
